return {
  -- {
  --   "petertriho/nvim-scrollbar",
  --   config = function()
  --     require("scrollbar").setup({
  --       marks = {
  --         Cursor = {
  --           text = "",
  --           priority = 0,
  --           gui = nil,
  --           color = nil,
  --           cterm = nil,
  --           color_nr = nil, -- cterm
  --           highlight = "Normal",
  --         }
  --       }
  --     })
  --   end
  -- },
  -- {
  --   "kevinhwang91/nvim-hlslens",
  --   config = function()
  --     require("scrollbar.handlers.search").setup({})
  --   end,
  -- },
  -- {
  --   "lewis6991/gitsigns.nvim",
  --   config = function()
  --     require('gitsigns').setup()
  --     require("scrollbar.handlers.gitsigns").setup()
  --   end
  -- }
}
